### ISSUE TITLE
PHP 8 anomaly

### ISSUE THREAD

**Issue by drbyte** [tightenco/collect#249]
Using PHP 7.4, running `composer require tightenco/collect` installs `v8.15.0`
Using PHP 8.0, running `composer require tightenco/collect` installs `v5.6.33`

I think it's because in the laravel-55-ongoing branch you say `"php": ">=7.0",`:
https://github.com/tighten/collect/blob/laravel-5.5-ongoing/composer.json

... but in newer branches you constrain it to 7.x, eg: `"php": "^7.2",`
https://github.com/tighten/collect/blob/laravel-8-ongoing/composer.json

It seems really strange to run `composer update` on PHP 8 and get `tightenco/collect` downgraded from 8.15.0 to 5.6.33.

**Comment by drbyte** [comment]
Easy example to reproduce: install PHP 8 with Valet and run `composer global update`

**Comment by mattstauffer** [comment]
Ouchhhhhh :/

I know we can fix that in ongoing releases but it'll still be a problem because all the old releases have that constraint. Best solution going forward is to get a release that supports PHP 8.

@jamisonvalenta Is there any reason not to update the `composer.json` to also support 8.0? This is what `illuminate/support` requires:  `"php": "^7.3|^8.0",`

**Comment by mattstauffer** [comment]
If I'm looking at the diff correctly, it's gonna be a valid constraint as of 8.12:

https://github.com/illuminate/collections/releases/tag/v8.12.0

**Comment by jamisonvalenta** [comment]
@mattstauffer No reason on my part to not update `composer.json` to `"php": "^7.3|^8.0"`.  

I'm not sure how to best proceed with tagging, since we're directly tracking `collections`'s tags. Is it preferable to make that update on the most recent code, and include that `composer.json` change in whatever the next `collections` release is, or do we need to go back to `8.12` and make a new minor version update (`8.12.1`) and update each of the tags.  

I think I prefer the former.

**Comment by mattstauffer** [comment]
@jamisonvalenta We've always worked to not re-publish releases, as frustrating as that will make our current situation, so let's update the code now and let it go out next time collections has a tag.

Thanks!

**Comment by mattstauffer** [comment]
https://github.com/tighten/collect/tree/v8.17.0

Fixed, hopefully. Testing now.

**Comment by mattstauffer** [comment]
Yep! Fixed!
