### ISSUE TITLE
Submit replace directive to illuminate/support

### ISSUE THREAD

**Issue by assertchris** [tightenco/collect#4]
https://getcomposer.org/doc/04-schema.md#replace

This is so that framework-agnostic libraries that depend on this one can be installed in Laravel applications.

**Comment by frankdejonge** [comment]
@assertchris Replacing packages is cumbersome, especially in long running projects, which the laravel project is. I think it would be be much easier to maintain when renaming the vendor to something other that Illuminate.

**Comment by mattstauffer** [comment]
@frankdejonge can you explain more? This is a new idea for me. If it helps as clarification, this will have perfect feature parity with illuminate support. So if anything depends on this its dependency will always be satisfied by illuminate support.

**Comment by frankdejonge** [comment]
@mattstauffer There's a gut feeling that makes me want to warn you, but I'm searching for the reasons. Partially it's about the "what is the truth" and "which source has precedence" issues. In theory, your source is a clone of the original, thus the original should have higher precedence than this package. But when people rely on this package, and with the addition of the replace clause your package will occupy the space rather than the illuminate package. Which is the inverted case of what I feel should happen. Also, I totally see where this is coming from, but conceptually something doesn't feel right.

**Comment by assertchris** [comment]
@frankdejonge I think there's a bit of confusion here. What I meant was that the illuminate packages should replace this one (specifically support). If someone has illuminate/support, they should use that instead of this, so that this does not attempt to load the same namespaces and classes into scope.

**Comment by frankdejonge** [comment]
@assertchris I see, that would be a lot better, however that solution doesn't really scale. In practise this may never happen, but since the laravel community is pretty damn big it might. What happens when 10 packages do this?

**Comment by assertchris** [comment]
Then they are all replaced by the official packages.

**Comment by frankdejonge** [comment]
And the "source" package would have to be aware of all of them in order for that to work. Which is a nuisance.

**Comment by assertchris** [comment]
In this case, the author of the source package has approved the split. It's somewhat of a special case.

**Comment by simensen** [comment]
👍 for having `illumiate/support` replace this package. If you aren't going to put the actual code in its own unique namespace it is the only option I'm aware of that will be safe/responsible.

**Comment by frankdejonge** [comment]
Just as a thought experiment, what would be against using an "own" namespace instead of `Illuminate`?

**Comment by mattstauffer** [comment]
Main reason I didn't up front was a) more work and complexity for when I automate it, b) more questions about whether or not it's a perfect duplicate, c) less clear attribution that it's all Taylor's work, d) less drop in ability since anyone who type hints or anything would all of a sudden not be able to use it. 

Thoughts?

Sent from Outlook Mobile




On Tue, May 3, 2016 at 4:58 AM -0700, "Frank de Jonge" <notifications@github.com> wrote:












Just as a thought experiment, what would be against using an "own" namespace instead of Illuminate?

**Comment by barryvdh** [comment]
Can't you just convince Taylor to split the collections class stuff from the support package to an 'official' laravel repo ;)

**Comment by mattstauffer** [comment]
Taylor was up for it. But I did about 50% of the work and the amount of work you have to duplicate, between macroable and arr:: methods and stuff ends up making laravel 's code base way more awful for a relatively edge case need. 

Sent from Outlook Mobile




On Tue, May 3, 2016 at 5:03 AM -0700, "Barry vd. Heuvel" <notifications@github.com> wrote:












Can't you just convince Taylor to split the collections class stuff from the support package to an 'official' laravel repo ;)

**Comment by barryvdh** [comment]
I do have to agree with Frank that this doesn't really 'feel right', unless you can indeed force preference for the original Laravel package. It _should_ be mostly compatible, but if some package relies on the 2% you're missing here, and no way to tell which class will be loaded (this repo or the 'real' package), it's just waiting for conflicts..

**Comment by assertchris** [comment]
@barryvdh but there is a way to know which will be loaded - if the official package has a `replace` object specifying this package, the official package will always be loaded. That certainly is the reason I created this issue.

**Comment by mattstauffer** [comment]
The 2% is a test for an eloquent collection that shouldn't be in here. Zero functionality difference. 
If I stay in the same namespace I will either pr "replace" support to illuminate--the point of this particular issue we are chatting in--or put huge warnings to package authors. 
Thanks for input 👍

Sent from Outlook Mobile




On Tue, May 3, 2016 at 5:09 AM -0700, "Barry vd. Heuvel" <notifications@github.com> wrote:












I do have to agree with Frank that this doesn't really 'feel right', unless you can indeed force preference for the original Laravel package. It should be mostly compatible, but if some package relies on the 2% you're missing here, and no way to tell which class will be loaded (this repo or the 'real' package), it's just waiting for conflicts..

**Comment by barryvdh** [comment]
@assertchris Yes that's what I meant. I know it's possible, but Taylor still needs to accept it ;). If it's fully compatible and will be replaced with the official support when possible, there probably isn't a problem :)

**Comment by frankdejonge** [comment]
Anyway, sorry to derail this discussion. I've put forward the concerns I have with this solution. It seems these concerns are not shared (which is perfectly fine of course). Carry on :)

**Comment by irazasyed** [comment]
Glad I checked the issue section and thanks for opening this @assertchris.

I wanted to use this for a project but was concerned about conflicts when using with Laravel/Lumen. Having an official repo for collections would be great :)

+1 for same namespace and PR to "replace" @mattstauffer.

**Comment by mattstauffer** [comment]
@frankdejonge Not sure if I would describe at as these concerns not being shared, but rather I've never done this before.. I'm doing my best to consider the possible negative impacts of choosing the course we have and, while I have had several general worries that it'll cause a conflict, I can't come up with any concrete ways it will--and neither has anyone yet, as far as I can see.

I'm 100% open to feedback, especially before too many people have adopted this. If Frank or anyone else have any concrete concerns with doing this in the Illuminate namespace instead of a Tightenco namespace, please speak up now.

**Comment by frankdejonge** [comment]
@mattstauffer I've mentioned the possibility of double/co- installs, which you say shouldn't and won't happen (but it wil, I promise ;)) , and the inverted dependency relation (project overwriting the "fork"), which you say also isn't a problem. But I'm pretty sure if random people from the community start doing this, it's going to be an issue. But if you think that's all minor and manageable, it's all fine by me. So I _would_ say you don't share the concerns ;) which is fine. I'm only here to try and help :)

Another suggestion, as suggested, would be to have an actual illuminate/collection package, which woud be the preferred way. That way there won't be the need for duplication. But it would mean the implementation would have to ship with the interfaces, which deviates from the current package-plitting pattern taylor seems to have.

**Comment by mattstauffer** [comment]
@frankdejonge <3 thanks bud.

Double/co-installs would be the fault of the individual coder (assuming we get the `replace` directive set up correctly) and I literally do not care. :) Yes, it might be a pain in the butt some times; if it gets so awful I can't handle it I'll shut it down. If I do end up doing, or complaining, please feel free to link to this comment with a giant troll graphic :)

Inverted dependency will not be a problem (assuming we get the `replace` directive set up correctly), because Composer will be smart enough to replace it.

Not sure what you mean about random people from the community--do you mean this is a problem if more people start splitting off sub-components? If so, then the concern you're addressing is: "At what point will Laravel/Illuminate be too clogged up by rando components PRing `replace` directives that we'll point back to this day and say 'DAMN MATT STAUFFER FOR STARTING THIS FLOOD'?" I understand that concern. I HOPE this is a unique case because collections are seeing a huge level of interest from outside the Laravel community, but there's at least a modest push-back on bringing in the entire Illuminate\Support package just for Collections. Is it valid? I don't know; if I thought it were *entirely* un-founded I wouldn't've done this. Additionally, I think this package can be a boost for folks A) loving Laravel, B) trying out functional/collection pipeline programming elsewhere, and C) eventually discovering Laravel is amazeballs and switching over.. so there's benefit for Laravel.

Finally, the Illuminate\Collection idea. That's what I did first; I started a PR to Illuminate to split Collection out, and chatted with Taylor some about how to do it well. Originally we had the idea to have a base Collection that didn't have Jsonable or Arrayable and brought the Macroable trait methods in manually, but that quickly spiraled into crazy amounts of code duplication when I discovered just how many `Arr::` methods (and which helpers) Collection uses. It was a whole bunch of work that would muddy up the Illuminate code base for the sake of a some what edge case need. So I dropped it, and did this instead.

**Comment by barryvdh** [comment]
Soo I see https://github.com/laravel/framework/pull/14118 from @eFrane now

**Comment by eFrane** [comment]
Whoops. I guess I should have checked here first.

**Comment by mattstauffer** [comment]
@eFrane That's not a problem at all! I think in the end I didn't see any reasons *not* to submit a replace directive.

**Comment by mattstauffer** [comment]
Done: https://github.com/laravel/framework/pull/14118

**Comment by holtkamp** [comment]
mmm, I "think" the following case is related, caused me some frustrations:

- was happily using ```"tightenco/collect": "^5.3"``` in my ```composer.json```
- thought [these macro's](https://github.com/spatie/laravel-collection-macros) would be nice to have
- added ```"spatie/laravel-collection-macros": "@stable"``` to my ```composer.json```
 - ```"spatie/laravel-collection-macros"``` [depends on ```"illuminate/support"```](https://github.com/spatie/laravel-collection-macros/blob/cccf84ef74b98554b3638ef8b336aaef1b66e47c/composer.json#L26) 
 - ```"illuminate/support"``` ```5.2.x``` gets installed (which obviously differs from 5.3)

I concluded that I can not use both:

- https://github.com/tightenco/collect
- https://github.com/spatie/laravel-collection-macros

Does anyone have a suggestions on an approach which **does** allow me to install the macro's and does **not** depend on the complete ```"illuminate/support"``` package?

**Comment by holtkamp** [comment]
Slightly related: https://github.com/spatie/laravel-collection-macros/issues/18

Thought of having this repo ```replace``` the collection part of ```illuminate/support```, but since that is not an isolation section, this is currently not an option 😢

**Comment by cristiangrama** [comment]
Let's say I create a package (api wrapper) with this package as a dependency and I choose the ^5.3 version. Someone then will install my package in a Laravel 5.5 version. What would happen then? I suppose the dependency would not be satisfiable and my package would not be able to be installed?
