### ISSUE TITLE
Other helper methods?

### ISSUE THREAD

**Issue by irazasyed** [tightenco/collect#7]
Can we get other helper methods like `array_get` and stuff?

I use them in a project that pulls in the support package.

I can send a PR if you're okay with it? I don't see any contributing guidelines BTW.

**Comment by mattstauffer** [comment]
Collections only, sorry! The only helpers we have here are because they're required in order for collections to work. I'll work on getting contributing guidelines set up, but basically, nothing goes in unless it's absolutely required to support collections. Thanks!

Sent from Outlook Mobile




On Tue, May 3, 2016 at 10:43 AM -0700, "Syed Irfaq R." <notifications@github.com> wrote:












Can we get other helper methods like array_get and stuff?



I use them in a project that pulls in the support package.



I can send a PR if you're okay with it? I don't see any contributing guidelines BTW.
